#pragma once

#ifdef AUDIO_ENABLE
#define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#define MIDI_BASIC

#define TAPPING_TERM 200

#define ENCODER_RESOLUTION 4

#define RGB_MATRIX_STARTUP_SPD 60

#define ORYX_CONFIGURATOR

#define PROGRESS_0_INDICATOR 0
#define PROGRESS_1_INDICATOR 1
#define PROGRESS_2_INDICATOR 2
#define PROGRESS_3_INDICATOR 3
