#ifdef KEYBOARD_planck_ez
  #define _SAFE_RANGE EZ_SAFE_RANGE
#else
  #define _SAFE_RANGE SAFE_RANGE
#endif

#define MT_LSFT_SPC MT(MOD_LSFT, KC_SPACE)

#define QWERTY_L3 KC_Q, KC_W, KC_E, KC_R, KC_T
#define QWERTY_R3 KC_Y, KC_U, KC_I, KC_O, KC_P
#define QWERTY_L2 KC_A, KC_S, KC_D, KC_F, KC_G
#define QWERTY_R2 KC_H, KC_J, KC_K, KC_L, KC_SCLN
#define QWERTY_L1 KC_Z, KC_X, KC_C, KC_V, KC_B
#define QWERTY_R1 KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH

#define LOWER_SYMBOLS_R KC_GRAVE, KC_UNDS, KC_MINUS, KC_PLUS, KC_EQUAL, KC_PIPE
#define NUMBERS_L KC_1, KC_2, KC_3, KC_4, KC_5
#define NUMBERS_R KC_6, KC_7, KC_8, KC_9, KC_0
#define NUMBER_SYMBOLS_L KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC
#define NUMBER_SYMBOLS_R KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN

#define RGB_L1 RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI
#define RGB_L2 RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD

#define AU_R1 MU_TOG, AU_TOG
#define AU_R2 MU_MOD

#define F_L KC_F1, KC_F2, KC_F3, KC_F4,  KC_F5,  KC_F6
#define F_R KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12

#define FN_L3 XXXXXXX, XXXXXXX,    XXXXXXX,    KC_MS_UP,       XXXXXXX,     TERRAFORM
#define FN_L2 KC_CAPS, KC_MS_BTN1, KC_MS_LEFT, KC_MS_DOWN,     KC_MS_RIGHT, KC_MS_BTN2
#define FN_L1 XXXXXXX, XXXXXXX,    XXXXXXX,    GIT_COMMIT_MSG, XXXXXXX,     XXXXXXX

#define FN_R3 XXXXXXX, XXXXXXX, KC_UP,   XXXXXXX, XXXXXXX,  XXXXXXX
#define FN_R2 GIT,     XXXXXXX, KC_LEFT, KC_DOWN, KC_RIGHT, XXXXXXX
#define FN_R1 XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX

enum userspace_custom_keycodes {
  GIT = _SAFE_RANGE,
  GIT_COMMIT_MSG,
  TERRAFORM,
};

enum tap_dances {
  TD_LBRACKETS,
  TD_RBRACKETS
};
