#ifdef KEYBOARD_planck_ez
  #define _SAFE_RANGE EZ_SAFE_RANGE
#else
  #define _SAFE_RANGE SAFE_RANGE
#endif

#define MT_LSFT_SPC MT(MOD_LSFT, KC_SPACE)

#define LOWER_SYMBOLS_R KC_GRAVE, KC_UNDS, KC_MINUS, KC_PLUS, KC_EQUAL, KC_PIPE
#define NUMBERS_L KC_1, KC_2, KC_3, KC_4, KC_5
#define NUMBERS_R KC_6, KC_7, KC_8, KC_9, KC_0
#define NUMBER_SYMBOLS_L KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC
#define NUMBER_SYMBOLS_R KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN

enum userspace_custom_keycodes {
  GIT = _SAFE_RANGE,
  GIT_COMMIT_MSG,
  TERRAFORM,
};

enum tap_dances {
  TD_LBRACKETS,
  TD_RBRACKETS
};
